/*Targil Kita 1*/

/*1*/
SELECT ENAME,SAL
FROM EMP
WHERE ENAME LIKE 'S%' AND SAL > 2000;

/*2*/
SELECT DEPTNO,AVG(SAL)
FROM EMP
WHERE DEPTNO = 10 group by DEPTNO;

/*3*/
SELECT COUNT(DEPTNO)
FROM EMP
WHERE DEPTNO = 10;

/*4*/
SELECT JOB,SAL
FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

/*5*/
SELECT ENAME,SAL
FROM EMP
WHERE JOB LIKE 'CLERK';

/*6*/
SELECT AVG(SAL)
FROM EMP
WHERE JOB LIKE 'CLERK';

/*7*/
SELECT *
FROM EMP
WHERE JOB NOT LIKE 'CLERK';

/*8*/
SELECT *
FROM EMP
WHERE DEPTNO != 20;

/*9*/
SELECT *
FROM EMP
WHERE ENAME LIKE '%RK';

/*10*/
SELECT *
FROM EMP
WHERE ENAME LIKE 'TURNER';

/*11*/
SELECT *
FROM EMP
WHERE MGR = 7566 AND HIREDATE > to_date('2/12/1981','dd/mm/yyyy');

/*12*/
SELECT ENAME,EMPNO
FROM EMP
WHERE HIREDATE BETWEEN to_date('3/12/1981','dd/mm/yyyy') AND to_date('21/1/1982','dd/mm/yyyy');
