DROP TABLE STUDENTS;
CREATE TABLE STUDENTS
(
ID  NUMBER(6),
LastName VARCHAR2(20),
FirstName VARCHAR2(10),
Address VARCHAR2(10),
BirthDay DATE,
GroupId NUMBER(3)
);

INSERT INTO STUDENTS VALUES(101,'Solin','Dan','Beer-Sheva',to_date('01/02/1985','dd/mm/yy'),11);

ALTER TABLE STUDENTS ADD AvgMark NUMBER(5,2) DEFAULT 0;

INSERT INTO STUDENTS VALUES(102,'Tal','Ruti','Tel-Aviv',to_date('10/7/1988','dd/mm/yy'),12,70);
INSERT INTO STUDENTS VALUES(103,'Kohen','Yossi','Dimona',to_date('01/8/1987','dd/mm/yy'),11,80);
INSERT INTO STUDENTS VALUES(104,'Toys','Vered','Tel-Aviv',to_date('15/9/1988','dd/mm/yy'),12,90);

ALTER TABLE STUDENTS MODIFY Address VARCHAR2(15);

DROP TABLE STUDENTS2;
CREATE TABLE STUDENTS2
(
ID  NUMBER(6),
LastName VARCHAR2(20),
FirstName VARCHAR2(10),
Address VARCHAR2(15),
BirthDay DATE,
GroupId NUMBER(3),
AvgMark Number(5,2)
);

INSERT INTO STUDENTS2
SELECT * FROM STUDENTS

